# Generated by Django 5.1.3 on 2024-11-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(choices=[('UA', 'Unida Administrativa'), ('UJ', 'Unidad Juridica'), ('UF', 'Unidad de Fiscalizacion'), ('AE', 'Aeropuerto El Alto'), ('PNL', 'Penal'), ('GYD', 'Gestion y Despachos'), ('SI', 'Secretaria Interior'), ('SG', 'Secretaria Gerencia'), ('VI', 'Ventanilla Interior'), ('VG', 'Ventanilla Gerencia'), ('CMS', 'Comisos'), ('UC', 'UCOE'), ('DP', 'Disposicon'), ('CC', 'Cobranza Coactiva'), ('AG', 'Archivos Gerencia'), ('AI', 'Archivos Interior'), ('TR', 'Transito'), ('PT', 'Plataforma'), ('SIS', 'Sistemas'), ('CBJ', 'Administracion Cobija'), ('CH', 'CHARAÑA'), ('DS', 'Desaguadero'), ('PH', 'PIA Huarina'), ('PG', 'PIA Guaqui'), ('PBJ', 'PIA Bojtilaca'), ('PAA', 'PIA Achica Arriba'), ('PP', 'PIA Patacamaya')], max_length=3)),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
    ]
