# Generated by Django 5.1 on 2024-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.AddField(
            model_name='task',
            name='unidad',
            field=models.CharField(choices=[('UA', 'Unida Administrativa'), ('UJ', 'Unidad Juridica'), ('UF', 'Unidad de Fiscalizacion'), ('AE', 'Aeropuerto El Alto'), ('PNL', 'Penal'), ('GYD', 'Gestion y Despachos'), ('SI', 'Secretaria Interior'), ('SG', 'Secretaria Gerencia'), ('VI', 'Ventanilla Interior'), ('VG', 'Ventanilla Gerencia'), ('CMS', 'Comisos'), ('UC', 'UCOE'), ('DP', 'Dispsicon'), ('CC', 'Cobranza Coactiva'), ('AG', 'Archivos Gerencia'), ('AI', 'Archivos Interior'), ('TR', 'Transito'), ('PT', 'Plataforma')], max_length=3, null=True),
        ),
    ]
