# Generated by Django 5.1.3 on 2024-11-28 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
