# Generated by Django 5.1 on 2024-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_title_task_nombre_remove_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='codigo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
