# Generated by Django 5.1 on 2024-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marca',
            field=models.CharField(choices=[('hp', 'HP'), ('xr', 'XEROX'), ('ot', 'OTRO')], max_length=2, null=True),
        ),
    ]
