# Generated by Django 5.1.3 on 2024-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='unidad',
            field=models.CharField(choices=[('Administrativa', 'Unida Administrativa'), ('Juridica', 'Unidad Juridica'), ('Fiscalizacion', 'Unidad de Fiscalizacion'), ('Aeropuerto', 'Aeropuerto El Alto'), ('Penal', 'Penal'), ('Gestion', 'Gestion'), ('Despachos', 'Despachos'), ('Secretaria Interior', 'Secretaria Interior'), ('Secretaria Gerencia', 'Secretaria Gerencia'), ('Ventanilla Interior', 'Ventanilla Interior'), ('Ventanilla Gerencia', 'Ventanilla Gerencia'), ('Comisos', 'Comisos'), ('Ucoe', 'UCOE'), ('Disposicion', 'Disposicon'), ('Coactiva', 'Cobranza Coactiva'), ('Archivos Gerencia', 'Archivos Gerencia'), ('Archivos Interior', 'Archivos Interior'), ('Transito', 'Transito'), ('Plataforma', 'Plataforma'), ('Sistemas', 'Sistemas'), ('Administracion Cobija', 'Administracion Cobija'), ('Charaña', 'Charaña'), ('Desaguadero', 'Desaguadero'), ('Huarina', 'PIA Huarina'), ('Guaqui', 'PIA Guaqui'), ('Bojtilaca', 'PIA Bojtilaca'), ('Achica Arriba', 'PIA Achica Arriba'), ('Patacamaya', 'PIA Patacamaya')], max_length=30),
        ),
    ]
