# Generated by Django 5.1 on 2024-09-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_marcas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='marcas',
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(choices=[('UA', 'Unida Administrativa'), ('UJ', 'Unidad Juridica'), ('UF', 'Unidad de Fiscalizacion'), ('AE', 'Aeropuerto El Alto'), ('PNL', 'Penal'), ('GYD', 'Gestion y Despachos'), ('SI', 'Secretaria Interior'), ('SG', 'Secretaria Gerencia'), ('VI', 'Ventanilla Interior'), ('VG', 'Ventanilla Gerencia'), ('CMS', 'Comisos'), ('UC', 'UCOE'), ('DP', 'Dispsicon'), ('CC', 'Cobranza Coactiva'), ('AG', 'Archivos Gerencia'), ('AI', 'Archivos Interior'), ('TR', 'Transito'), ('PT', 'Plataforma')], max_length=3, null=True)),
                ('marcas', models.CharField(choices=[('hp', 'HP'), ('ep', 'EPSON'), ('xr', 'XEROX'), ('fj', 'FUJITSU'), ('ot', 'OTRO')], max_length=2, null=True)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
