# Generated by Django 5.1 on 2024-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_marcas_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marcas',
            field=models.CharField(choices=[('hp', 'HP'), ('ep', 'EPSON'), ('xr', 'XEROX'), ('fj', 'FUJITSU'), ('ot', 'OTRO')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
