# Generated by Django 5.1 on 2024-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_marcas_delete_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modelo',
            field=models.CharField(choices=[('smg', 'SAMSUNG'), ('hp', 'HP'), ('lg', 'LG'), ('dll', 'DELL'), ('bnq', 'BENQ'), ('ot', 'OTRO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tipo',
            field=models.CharField(choices=[('dh', 'DISCO DURO'), ('sd', 'DISCO SOLIDO')], max_length=3, null=True),
        ),
    ]
