# Generated by Django 5.1 on 2024-09-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Marca',
            new_name='model',
        ),
    ]
