# Generated by Django 5.1 on 2024-09-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_marca_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='model',
        ),
    ]
