# Generated by Django 5.1 on 2024-09-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='model',
            field=models.CharField(choices=[('hp', 'HP'), ('dll', 'DELL'), ('ac', 'ACER'), ('lnv', 'LENOVO')], max_length=3, null=True),
        ),
    ]
