# Generated by Django 5.1 on 2024-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cpu',
            field=models.CharField(choices=[('hp', 'HP'), ('dll', 'DELL'), ('ln', 'LENOVO'), ('lg', 'LG'), ('ot', 'otro')], max_length=3, null=True),
        ),
    ]
