# Generated by Django 5.1.2 on 2024-11-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='unidad',
            field=models.CharField(choices=[('UA', 'Unida Administrativa'), ('UJ', 'Unidad Juridica'), ('UF', 'Unidad de Fiscalizacion'), ('AE', 'Aeropuerto El Alto'), ('PNL', 'Penal'), ('GYD', 'Gestion y Despachos'), ('SI', 'Secretaria Interior'), ('SG', 'Secretaria Gerencia'), ('VI', 'Ventanilla Interior'), ('VG', 'Ventanilla Gerencia'), ('CMS', 'Comisos'), ('UC', 'UCOE'), ('DP', 'Dispsicon'), ('CC', 'Cobranza Coactiva'), ('AG', 'Archivos Gerencia'), ('AI', 'Archivos Interior'), ('TR', 'Transito'), ('PT', 'Plataforma'), ('SIS', 'Sistemas')], max_length=3, null=True),
        ),
    ]
