# Generated by Django 5.1.2 on 2024-11-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='unidad',
            field=models.CharField(choices=[('UA', 'Unida Administrativa'), ('UJ', 'Unidad Juridica'), ('UF', 'Unidad de Fiscalizacion'), ('AE', 'Aeropuerto El Alto'), ('PNL', 'Penal'), ('GYD', 'Gestion y Despachos'), ('SI', 'Secretaria Interior'), ('SG', 'Secretaria Gerencia'), ('VI', 'Ventanilla Interior'), ('VG', 'Ventanilla Gerencia'), ('CMS', 'Comisos'), ('UC', 'UCOE'), ('DP', 'Disposicon'), ('CC', 'Cobranza Coactiva'), ('AG', 'Archivos Gerencia'), ('AI', 'Archivos Interior'), ('TR', 'Transito'), ('PT', 'Plataforma'), ('SIS', 'Sistemas'), ('CBJ', 'Administracion Cobija'), ('CH', 'CHARAÑA'), ('DS', 'Desaguadero'), ('PH', 'PIA Huarina'), ('PG', 'PIA Guaqui'), ('PBJ', 'PIA Bojtilca'), ('PAA', 'PIA Achica Arriba'), ('PP', 'PIA Patacamaya')], max_length=3, null=True),
        ),
    ]
